server:
  port: 1002

spring:
  application:
    name: service-message
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    virtual-host: /rabbit
    template:
      mandatory: true
    connection-timeout: 15000

rabbit:
  exchange: rabbit_exchange
  queue: rabbit_queue
  routingKey: com.jamie.#
