server:
  port: 1002

spring:
  profiles:
    active: dev
  application:
    name: service-message
  rabbitmq:
    publisher-confirms: true
    publisher-returns: true
    virtual-host: /rabbit
    template:
      mandatory: true
    connection-timeout: 15000

rabbit:
  exchange: rabbit_exchange
  queue: rabbit_queue
  routingKey: com.jamie.#
