server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000

