spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_resource?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070