spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_a?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest