server:
  port: 1001

spring:
  application:
    name: service-a
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validation-query: select 1 from DUAL
      validation-query-timeout: 6000
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
      pool-prepared-statements: false
  rabbitmq:
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: manual
        max-concurrency: 10
        concurrency: 5

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

